# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/db_person?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSl=false
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update